language: java
branches:
  only:
    - develop
jdk: openjdk11
cache:
  directories:
    - $HOME/.m2
services:
  - docker
env:
  global:
    - DOCKER_REGISTRY=openshift-registry.adorsys.de
    - IMAGE=${DOCKER_REGISTRY}/bg-monitoring-dev/bg-monitoring-server:build_${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT}
    - OPENSHIFT_SERVER=https://openshift.adorsys.de
    - OC_VERSION=v3.11.0
    - OC_VERSION_COMMIT=0cbc58b
    - HELM_VERSION=v2.12.2
install: skip
script:
  - mvn install -B
  - docker build -t $IMAGE .
deploy:
  - provider: script
    skip_cleanup: true
    script: bash devops/scripts/deploy.sh
    on:
      branch: develop
