{{ if and .Values.grafana.enabled .Values.grafana.route.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
{{- with .Values.grafana.route.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ template "bg-monitoring.fullname" . }}-grafana
  labels:
{{ include "bg-monitoring.labels" . | indent 4 }}
    app.kubernetes.io/component: grafana
spec:
  host: {{ tpl .Values.grafana.route.host . | quote }}
  port:
    targetPort: default
{{- with .Values.grafana.route.tls }}
  tls:
{{ toYaml . | indent 4 }}
{{- end }}
  to:
    kind: Service
    name: {{ template "bg-monitoring.fullname" . }}-grafana
    weight: 100
    wildcardPolicy: None
{{- end }}
