apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-grafana
spec:
  selector:
    deploymentconfig: {{ .Chart.Name }}-grafana
  ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
