{{ if .Values.grafana.enabled }}
---
apiVersion: v1
kind: Service
metadata:
{{- with .Values.grafana.serviceAnnotations }}
   annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ template "bg-monitoring.fullname" . }}-grafana
  labels:
{{ include "bg-monitoring.labels" . | indent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: ClusterIP
  ports:
    - name: default
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
{{ include "bg-monitoring.matchLabels" . | indent 4 }}
    app.kubernetes.io/component: grafana
{{- end }}
