apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ .Chart.Name }}-influxdb
spec:
  selector:
    app: {{ .Chart.Name }}-influxdb
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-influxdb
    spec:
      containers:
        - name: {{ .Chart.Name }}-influxdb
          image: influxdb:1.7.9
          ports:
            - containerPort: 8086
          env:
            - name: INFLUXDB_DB
              value: bg_monitoring
            - name: INFLUXDB_WRITE_USER
              valueFrom:
                secretKeyRef:
                  name: influxdb-credentials
                  key: write-access-username
            - name: INFLUXDB_WRITE_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: influxdb-credentials
                  key: write-access-password
            - name: INFLUXDB_READ_USER
              valueFrom:
                secretKeyRef:
                  name: influxdb-credentials
                  key: read-access-username
            - name: INFLUXDB_READ_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: influxdb-credentials
                  key: read-access-password
          volumeMounts:
            - name: influxdb-volume
              mountPath: /var/lib/influxdb
      volumes:
        - name: influxdb-volume
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-influxdb
