apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ .Chart.Name }}-influxdb
spec:
  selector:
    app: {{ .Chart.Name }}-influxdb
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-influxdb
    spec:
      containers:
        - name: {{ .Chart.Name }}-influxdb
          image: influxdb:1.7.9
          ports:
            - containerPort: 8086
          volumeMounts:
            - name: influxdb-volume
              mountPath: /var/lib/influxdb
      volumes:
        - name: influxdb-volume
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-influxdb
