{{- if and .Values.influxdb.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bg-monitoring.fullname" . }}-influxdb
  labels:
{{ include "bg-monitoring.labels" . | indent 4 }}
    app.kubernetes.io/component: influxdb
type: Opaque
data:
  {{- range $name, $value := .Values.influxdb.secrets }}
  {{- if not (empty $value) }}
  {{ $name }}: {{ tpl (toString $value) $ | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
