apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-influxdb
spec:
  selector:
    deploymentconfig: {{ .Chart.Name }}-influxdb
  ports:
    - port: 8086
      protocol: TCP
      targetPort: 8086
