{{ if .Values.influxdb.enabled }}
---
apiVersion: v1
kind: Service
metadata:
{{- with .Values.influxdb.serviceAnnotations }}
   annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ template "bg-monitoring.fullname" . }}-influxdb
  labels:
{{ include "bg-monitoring.labels" . | indent 4 }}
    app.kubernetes.io/component: influxdb
spec:
  type: ClusterIP
  ports:
    - port: 8086
      protocol: TCP
      targetPort: 8086
  selector:
{{ include "bg-monitoring.matchLabels" . | indent 4 }}
    app.kubernetes.io/component: influxdb
{{- end }}
