apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ .Chart.Name }}-app
spec:
  selector:
    app: {{ .Chart.Name }}-app
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-app
    spec:
      containers:
        - name: {{ .Chart.Name }}-app
          image: "{{ .Values.image }}"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_RABBITMQ_HOST
              value: {{ .Chart.Name }}-rabbitmq
            - name: BG_MONITORING_SERVER_INFLUXDB_URL
              value: "http://{{ .Chart.Name }}-influxdb:8086"
            - name: BG_MONITORING_SERVER_INFLUXDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: influxdb-credentials
                  key: write-access-username
            - name: BG_MONITORING_SERVER_INFLUXDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: influxdb-credentials
                  key: write-access-password
