{{ if .Values.app.enabled }}
---
apiVersion: v1
kind: Service
metadata:
{{- with .Values.app.serviceAnnotations }}
   annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ template "bg-monitoring.fullname" . }}-app
  labels:
{{ include "bg-monitoring.labels" . | indent 4 }}
    app.kubernetes.io/component: app
    app: bg-monitoring
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
{{ include "bg-monitoring.matchLabels" . | indent 4 }}
    app.kubernetes.io/component: app
    app: bg-monitoring
{{- end }}
