apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ .Chart.Name }}-rabbitmq
spec:
  selector:
    app: {{ .Chart.Name }}-rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-rabbitmq
    spec:
      containers:
        - name: {{ .Chart.Name }}-rabbitmq
          image: rabbitmq:3.8.1-management
          ports:
            - containerPort: 5672
          env:
            - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
              value: -rabbitmq_management load_definitions "/mnt/etc/rabbitmq/rabbitmq.definitions.json"
          volumeMounts:
            - name: rabbitmq-volume
              mountPath: /var/lib/rabbitmq
            - name: rabbitmq-definitions-volume
              mountPath: /mnt/etc/rabbitmq
      volumes:
        - name: rabbitmq-volume
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-rabbitmq
        - name: rabbitmq-definitions-volume
          secret:
            secretName: rabbitmq-definitions-secret
