{{- if .Values.rabbitmq.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "bg-monitoring.fullname" . }}-rabbitmq
  labels:
{{ include "bg-monitoring.labels" . | indent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
{{- end }}