{{- if and .Values.rabbitmq.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bg-monitoring.fullname" . }}-rabbitmq
  labels:
{{ include "bg-monitoring.labels" . | indent 4 }}
    app.kubernetes.io/component: rabbitmq
type: Opaque
data:
  {{- range $name, $value := .Values.rabbitmq.secrets }}
  {{- if not (empty $value) }}
  {{ $name }}: {{ tpl (toString $value) $ | b64enc | quote }}
  {{- end }}
  {{- end }}
  rabbitmq.definitions.json: |
    {{- (.Files.Get (.Values.rabbitmq.data.config) | b64enc ) | nindent 4 }}  
{{- end }}
