apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-rabbitmq
spec:
  selector:
    deploymentconfig: {{ .Chart.Name }}-rabbitmq
  ports:
    - port: 5672
      protocol: TCP
      targetPort: 5672
