{{ if .Values.rabbitmq.enabled }}
---
apiVersion: v1
kind: Service
metadata:
{{- with .Values.rabbitmq.serviceAnnotations }}
   annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ template "bg-monitoring.fullname" . }}-rabbitmq
  labels:
{{ include "bg-monitoring.labels" . | indent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  type: ClusterIP
  ports:
    - port: 5672
      protocol: TCP
      targetPort: 5672
  selector:
{{ include "bg-monitoring.matchLabels" . | indent 4 }}
    app.kubernetes.io/component: rabbitmq
{{- end }}
